ARG version
FROM almalinux:${version}
ARG sudheer
ARG vineela
RUN echo "sudheer is ${sudheer} vineela is ${vineela} "
CMD ["sleep", "100"]










# How do you check your OS version? cat /etc/*release